use std::fmt;

use crate::domain::block::BlockId;

pub const MAX_ALIAS_LENGTH: usize = 32;
pub const KID_LENGTH: usize = 12;

/// Human-readable representation of a Block.
///
/// An Alias may initially contain the KID generated by Keepld,
/// but the user may replace it with a custom alias.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Alias(String);

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AliasError {
    Empty,
    TooLong,
    ContainsWhitespace,
    ContainsControlCharacter,
    ContainsPathSeparator,
}

impl fmt::Display for AliasError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Empty => write!(f, "alias cannot be empty"),
            Self::TooLong => {
                write!(f, "alias cannot exceed {MAX_ALIAS_LENGTH} characters")
            }
            Self::ContainsWhitespace => {
                write!(f, "alias cannot contain whitespace")
            }
            Self::ContainsControlCharacter => {
                write!(f, "alias cannot contain control characters")
            }
            Self::ContainsPathSeparator => {
                write!(f, "alias cannot contain path separators")
            }
        }
    }
}

impl std::error::Error for AliasError {}

impl Alias {
    /// Creates a user-defined Alias after validating its invariants.
    pub fn new(value: impl Into<String>) -> Result<Self, AliasError> {
        let value = value.into();

        if value.is_empty() {
            return Err(AliasError::Empty);
        }

        if value.chars().count() > MAX_ALIAS_LENGTH {
            return Err(AliasError::TooLong);
        }

        if value.chars().any(char::is_control) {
            return Err(AliasError::ContainsControlCharacter);
        }

        if value.chars().any(char::is_whitespace) {
            return Err(AliasError::ContainsWhitespace);
        }

        if value.contains('/') || value.contains('\\') {
            return Err(AliasError::ContainsPathSeparator);
        }

        Ok(Self(value))
    }

    /// Creates the default 12-character KID from a BlockId.
    pub(crate) fn from_kid(block_id: &BlockId) -> Self {
        let uuid = block_id.as_uuid();
        let bytes = uuid.as_bytes();

        // The first 6 UUID bytes provide 48 bits, represented as
        // exactly 12 hexadecimal characters.
        let mut kid = String::with_capacity(KID_LENGTH);

        for byte in bytes.iter().take(6) {
            use std::fmt::Write;
            write!(&mut kid, "{byte:02x}").expect("writing to String cannot fail");
        }

        debug_assert_eq!(kid.len(), KID_LENGTH);

        Self(kid)
    }

    /// Returns the Alias as a string slice.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl AsRef<str> for Alias {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl fmt::Display for Alias {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accepts_valid_alias() {
        let alias = Alias::new("project-main").unwrap();

        assert_eq!(alias.as_str(), "project-main");
    }

    #[test]
    fn rejects_empty_alias() {
        assert_eq!(Alias::new(""), Err(AliasError::Empty));
    }

    #[test]
    fn rejects_alias_longer_than_32_characters() {
        let value = "a".repeat(33);

        assert_eq!(Alias::new(value), Err(AliasError::TooLong));
    }

    #[test]
    fn rejects_whitespace() {
        assert_eq!(
            Alias::new("project main"),
            Err(AliasError::ContainsWhitespace)
        );
    }

    #[test]
    fn rejects_control_characters() {
        assert_eq!(
            Alias::new("project\nmain"),
            Err(AliasError::ContainsControlCharacter)
        );
    }

    #[test]
    fn rejects_path_separators() {
        assert_eq!(
            Alias::new("project/main"),
            Err(AliasError::ContainsPathSeparator)
        );

        assert_eq!(
            Alias::new("project\\main"),
            Err(AliasError::ContainsPathSeparator)
        );
    }

    #[test]
    fn allows_unicode() {
        let alias = Alias::new("proyecto-á").unwrap();

        assert_eq!(alias.as_str(), "proyecto-á");
    }

    #[test]
    fn allows_exactly_32_characters() {
        let value = "a".repeat(32);

        assert!(Alias::new(value).is_ok());
    }

    #[test]
    fn kid_has_exactly_12_characters() {
        let block_id = BlockId::from_uuid(
            uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap(),
        );

        let alias = block_id.default_alias();

        assert_eq!(alias.as_str(), "550e8400e29b");
        assert_eq!(alias.as_str().chars().count(), KID_LENGTH);
    }

    #[test]
    fn kid_generation_is_deterministic() {
        let uuid = uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440000").unwrap();

        let first = BlockId::from_uuid(uuid).default_alias();
        let second = BlockId::from_uuid(uuid).default_alias();

        assert_eq!(first, second);
    }
}
